apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-kustomize-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-kustomize-test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: "*"
      recurse: false
    path: nginx
    repoURL: https://github.com/toshihiko-okubo/test-kustomize
    targetRevision: main
#  syncPolicy:
#    automated:
#      allowEmpty: false
#      prune: true
#      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/toshihiko-okubo/test-kustomize
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: false
