apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argo-kustomize-test
  labels:
    app: nginx
    version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
